# Generated by Django 3.2.4 on 2021-06-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0004_alter_addtask_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtask',
            name='Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
